<?php
/**
 * @file
 *
 */

/*
 * Implementation of hook_init()
 */
function nodeinfo_init() {

}

/**
 * Implements hook_node_insert.
 */

/**
 * Implements hook_node_presave().
 * Act on a node being inserted or updated.
 */
function nodeinfo_node_presave($node) {
  _nodeinfo_nodetitle_set_title($node);
}

/**
 * add automatic node title.
 */
function _nodeinfo_nodetitle_set_title(&$node) {
  /**
   * meeting
   */
  if ($node->type == 'meeting') {
    $node->title = t('Alliance Meeting');
  }

}
