<?php
/**
 * @file
 *
 */

/**
 * Implements hook_init()
 */
function libraryinfo_init() {
  drupal_add_library('libraryinfo', 'libraryinfo_jquery_ui');
  drupal_add_library('libraryinfo', 'libraryinfo_angularjs');
}

/**
 * Implements hook_library().
 *
   drupal_add_library('libraryinfo', 'libraryinfo_angularjs');
 *
 */
function libraryinfo_library() {
  $libraries = array();

  /**
   * "AngularJS "
   */
  $libraries['libraryinfo_angularjs'] = array(
    'title' => 'AngularJS',
    'version' => '1.4.7',
    'website' => 'https://angularjs.org/',
    'js' => array(
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.js' => array('type' => 'external'),
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-route.min.js' => array('type' => 'external'),
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-animate.min.js' => array('type' => 'external'),
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-aria.min.js' => array('type' => 'external'),
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-messages.min.js' => array('type' => 'external'),
      'https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-resource.min.js' => array('type' => 'external'),
      'https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.14.3/ui-bootstrap.js' => array('type' => 'external'),
      'https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.14.3/ui-bootstrap-tpls.min.js' => array('type' => 'external'),
    ),
  );

  /**
   * jQuery UI
   */
  $jquery_ui_path = libraries_get_path('jquery-ui-1.11.4') . '/';
  $libraries['libraryinfo_jquery_ui'] = array(
    'title' => 'jQuery UI',
    'version' => '1.11.4 ',
    'website' => 'http://jqueryui.com/',
    'js' => array(
      $jquery_ui_path . 'jquery-ui.min.js' => array(),
    ),
    'css' => array(
      $jquery_ui_path . 'jquery-ui.min.css' => array(),
    ),
  );


  /** - - - - - - return - - - - - - - - - - - - - - - - - - - - - - - - - -  */

  return $libraries;
}

